version: '3.5'

# THESE OVERRIDES ARE FOR DEVELOPMENT! DON'T USE THIS IN PRODUCTION!
services:
  caddy:
    environment:
      # Site will be available at https://localhost
      - PROD_HOST_NAME=http://localhost

  redis:
    ports:
      - "6379:6379"

  django:
    # Automatically reload Gunicorn when a file changes
    command: gunicorn webauthnio.wsgi -c gunicorn.cfg.py --reload
    environment:
      - DEBUG=true
      - RP_ID=localhost
      - RP_NAME=WebAuthn.io (Dev)
      - RP_EXPECTED_ORIGIN=http://localhost
